### ISSUE TITLE
New minor release with #113?

### ISSUE THREAD

**Issue by nickvaras** [SteveMacenski/spatio_temporal_voxel_layer#118]
Hi Steve, any plans for a new minor release that includes #113 soon?

**Comment by SteveMacenski** [comment]
Sure, why not. We have the nice 2 source observations work done too. In progress

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/20394

**Comment by nickvaras** [comment]
Woohoo! Thanks!
