### ISSUE TITLE
local costmap displays 

### ISSUE THREAD

**Issue by opendvd** [SteveMacenski/spatio_temporal_voxel_layer#121]
I'm puzzled about the display of local costmap. Thanks for your reading.
  If i set the **voxel_decay** params to be 1 or other value and delay model sets to be linear, the local_costmap has some delay to dispaly the obstacles. The front of the robot appears people, but the costmap can't display the obstacle of the people **immediately**. 
  If i set the **voxel_decay** params to be zero, the local_costmap displayed in rviz always **twinkles**, instead of continuous display.  So what should i do to display it immediately?
Thanks a lot for your reply.

**Comment by SteveMacenski** [comment]
This seems to be a visualization problem, no an issue in the codebase, please redirect for general costmap assistance to ros answers.
