### ISSUE TITLE
Plans for ROS 2?

### ISSUE THREAD

**Issue by tasilb** [SteveMacenski/spatio_temporal_voxel_layer#137]
What needs to get done to release STVL as  ROS 2 package?

**Comment by SteveMacenski** [comment]
Are you moving to ROS2?

Right now the state of perception in Navigation2 (ROS2's navigation client, very different from the existing navigation stack) is up in the air, I was going to wait until that was hammered out before migrating.

If you have a more immediate need for a Dashing build of STVL, I can help guide you through the migration process but I don't have the cycles this month (probably) to take too much of an active role in it

**Comment by SteveMacenski** [comment]
It doesn't sound like from my discussion on navigation2 that the costmap API is going to change, so porting this would be relatively simple.

**Comment by SteveMacenski** [comment]
As an update, I'm in the middle of a port. Its 80% done but the last 20% will take some time. I can push the branch to collaborate if someone's interested in taking on a couple features from my todo list

**Comment by SteveMacenski** [comment]
ROS2 branch is up.

It generally needs testing but otherwise its the first stab at a port

**Comment by SteveMacenski** [comment]
Complete and tested in simulation
