### ISSUE TITLE
GoogleCartographer + spatio_temporal_voxel_layer?

### ISSUE THREAD

**Issue by MrGitGo** [SteveMacenski/spatio_temporal_voxel_layer#139]
Can I use Google Cartographer for mapping and spatio temporal voxel layer for detecting obstacles? Is this constellation possible? I want to run them parallel

**Comment by MarcelSoler** [comment]
Yes you can! I've done it. 
Spatio temporal is a layer (pluggin) of navigation stack if you are already using the navigation stack to avoid obstacles  just add the layer like in the readme.

**Comment by SteveMacenski** [comment]
Seems resolved before I even woke up, thanks! 

:-)
