### ISSUE TITLE
Free space detection

### ISSUE THREAD

**Issue by patripfr** [SteveMacenski/spatio_temporal_voxel_layer#148]
Hi,
Does this implementation offer an explicit description of free space / see through voxels as it is done in octomap? Or are all unobserved voxels considered free? I could not find anything about this in the docu.

Best Patrick

**Comment by SteveMacenski** [comment]
I don’t understand your question

**Comment by patripfr** [comment]
nevermind, I found out about the frustum approach in between so that kind of answers my question

**Comment by SteveMacenski** [comment]
Ok!
