### ISSUE TITLE
Use of different data types than PointCloud2

### ISSUE THREAD

**Issue by SimonAntonin** [SteveMacenski/spatio_temporal_voxel_layer#169]
Hello,

i am a robotics beginner and would like to use stvl with another datatype than pointcloud2.
Can I use the STVL with depth cameras but different datatypes than PointCloud2? (How?)
Can I use sensor_msgs/Image ?

Thanks in advance.

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers, but the answer is no, you must use a pointcloud or laserscan
