### ISSUE TITLE
Working only the local costmap without the global costmap

### ISSUE THREAD

**Issue by DronistB** [SteveMacenski/spatio_temporal_voxel_layer#186]
Hi,
I'm trying use this great package for collision detection, but I want to use only the pointcloud of local costmap without the global costmap. (/move_base/local_costmap/rgbd_obstacle_layer/voxel_grid)
1. I've tried to launch the pkg like this:
```
    <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
      <rosparam file="$(find xtra_local_map)/costmap_common_params.yaml" command="load" ns="local_costmap" />
      <rosparam file="$(find xtra_local_map)/local_costmap_params.yaml" command="load" />
      <rosparam file="$(find xtra_local_map)/base_local_params.yaml" command="load" />
    </node>
```
But due to the fact that I'm not publishing map frame and just using visual odometry, I'm getting errors like this:
(I'm working in ODOM frame)

`[ WARN] [1605022996.467167676]: Timed out waiting for transform from base_link to map to become available before running costmap, tf error: canTransform: source_frame base_link does not exist.. canTransform returned after 0.100732 timeout was 0.1.
`

Is there any way to use just the point cloud generated with the spatio temporal voxel layer without all the other capabilities?
Thanks

(Working in melodic - spatio version 1.35)
(move base - 1.16.7)

**Comment by SteveMacenski** [comment]
Please ask for configuration assistance on ROS Answers.
