### ISSUE TITLE
vlp16 dones't show the voxel

### ISSUE THREAD

**Issue by chanzw** [SteveMacenski/spatio_temporal_voxel_layer#189]
Hello , I have a problem. I have installed the kinetic branch successfully. The pluins has worked .I can see it in the rostopic . But in RVIZ ,I choose the topic ,and It dones,t show the voxel. I run the rostopic echo, It doens't show nothing .So, I want to know the reason.But I can get  the velodyne_points    data.

 
![111](https://user-images.githubusercontent.com/44609132/104475154-b8c3f600-55f9-11eb-92dc-dae338201dcf.PNG)
![222](https://user-images.githubusercontent.com/44609132/104475165-bc577d00-55f9-11eb-9974-b92d106b9f17.PNG)
![333](https://user-images.githubusercontent.com/44609132/104475169-bd88aa00-55f9-11eb-8445-bbb823e7b5c2.PNG)

**Comment by SteveMacenski** [comment]
Do you have voxel grid publishing enabled?

**Comment by chanzw** [comment]
> Do you have voxel grid publishing enabled?

ok. I know it . Thank you.

**Comment by chanzw** [comment]
Hello ,The speed of the voxel clear is too slow.AndIs this problem related to computer performance？Or I can set a certain parameters.

**Comment by SteveMacenski** [comment]
That might be a question better for ROS answers with more detail.

Closing ticket since we answered the question in the ticket.

**Comment by chanzw** [comment]
> 
> 
> That might be a question better for ROS answers with more detail.
> 
> Closing ticket since we answered the question in the ticket.

thanks
