### ISSUE TITLE
Find voxel blobs - v1.5

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/spatio_temporal_voxel_layer#2]
- in connected-component to the static map (2D, later 3D as well)
- blobs not connected to map, static
- blobs that are moving not disconnected from static map

**Comment by SteveMacenski** [comment]
http://ai2-s2-pdfs.s3.amazonaws.com/363c/f3eb04c43932a97f2e48d8e2099b3783cd96.pdf

**Comment by tasilb** [comment]
FYI I'm "Access Denied" on your link.

**Comment by SteveMacenski** [comment]
same... that's annoying. That was so long ago I don't even know what was in that link. Probably some 3D clustering optimization.

**Comment by SteveMacenski** [comment]
This is going to be implemented in another project.
