### ISSUE TITLE
SpatioTemporalVoxelLayer plugin does not exist??

### ISSUE THREAD

**Issue by JackRen88** [SteveMacenski/spatio_temporal_voxel_layer#206]
Hello,everyone!
When I run the move_base launch file,there is a error below:
`terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  According to the loaded plugin descriptions the class spatio_temporal_voxel_layer::SpatioTemporalVoxelLayer with base class type costmap_2d::Layer does not exist. Declared types are  costmap_2d::InflationLayer costmap_2d::ObstacleLayer costmap_2d::StaticLayer costmap_2d::VoxelLayer
`
system :ubuntu 18.04,
ROS: melodic ros1
Have you ever encountered this problem and how to solve it?

**Comment by SteveMacenski** [comment]
Please ask on ros answers.
