### ISSUE TITLE
Could you provide a mapping demo that uses stvl

### ISSUE THREAD

**Issue by zorosmith** [SteveMacenski/spatio_temporal_voxel_layer#210]
Hello,
Thank you for your contribution to the community！
I am a new hand in navigation and trying to use stvl to mapping.
I have read your paper and readme about this project. And now, I am studying mapping with your code step by step. However, I have some questions while using your code. 
Could you provide a mapping demo that uses stvl? Any things that help to make sense how to use this code will be ok.
Thx a lot!

**Comment by SteveMacenski** [comment]
This is not a mapping library
