### ISSUE TITLE
ros melodic catkin_make error 

### ISSUE THREAD

**Issue by BADAL244** [SteveMacenski/spatio_temporal_voxel_layer#211]
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)

-- Configuring incomplete, errors occurred!
See also "/home/agx1/hector/build/CMakeFiles/CMakeOutput.log".
See also "/home/agx1/hector/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by SteveMacenski** [comment]
Ask on ros answers or google the error
