### ISSUE TITLE
add two depth cameras

### ISSUE THREAD

**Issue by gongyue666** [SteveMacenski/spatio_temporal_voxel_layer#215]
Hi, I want to fix two depth cameras in my robot, one is in front of the robot, the other one is back of the robot. How can I use these two cameras together with spatio_temporal_voxel_layer? One way is that merge the two pointclouds into a big one. Do you have other ideas?

**Comment by SteveMacenski** [comment]
You can definitely use 2+ observation sources in a single STVL layer! That is actually the implementation intent of this work 🙂. Simply define 2 sources and you should be good to go!

**Comment by gongyue666** [comment]
thx, I have seen the details
