### ISSUE TITLE
STVL stops publishing points immediately after startup

### ISSUE THREAD

**Issue by p0rys** [SteveMacenski/spatio_temporal_voxel_layer#216]
Hey,

i discovered a problem with the spatio temporal voxel layer on my simulated robot. When i start nav2 with STVL as local costmap layer it will publish the voxel grid (publish voxel = true) and the correct costmap but after these initial data it stops immediately. I can see that the layer is publishing messages (RVIz messages counter on /localcostmap/voxel_grid  increases ) but it does not contain any new points. The first found points will decay as expected.

Does anyone know why this happens?

- ROS Foxy 
- Nav2 deb packages
- "fox-devel" branch of STVL
- Gazebo 11
- "use_sim_time" is set on all nodes

<details>
  <summary>Config</summary>

    obstacle_3d_layer:
          plugin: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"
          transform_tolerance: 0.3
          publish_voxel_map: True
          track_unknown_space: True
          voxel_decay: 15.0
          observation_sources: camera_front camera_left camera_right camera_rear
          camera_front:
            topic: "/camera_front/depth/color/points"
            data_type: "PointCloud2"
            expected_update_rate: 0.0
            min_obstacle_height: 0.05
            max_obstacle_height: 2.0
            marking: True
            clearing: True
            obstacle_range: 3.0
            vertical_fov_angle: 0.994838
            horizontal_fov_angle: 1.50098
            decay_acceleration: 1.0
            clear_after_reading: True
          camera_left:
            topic: "/camera_left/depth/color/points"
            data_type: "PointCloud2"
            expected_update_rate: 0.0
            min_obstacle_height: 0.05
            max_obstacle_height: 2.0
            marking: True
            clearing: True
            obstacle_range: 3.0
            vertical_fov_angle: 0.994838
            horizontal_fov_angle: 1.50098
            decay_acceleration: 1.0
            clear_after_reading: True
          camera_right:
            topic: "/camera_right/depth/color/points"
            data_type: "PointCloud2"
            expected_update_rate: 0.0
            min_obstacle_height: 0.05
            max_obstacle_height: 2.0
            marking: True
            clearing: True
            obstacle_range: 3.0
            vertical_fov_angle: 0.994838
            horizontal_fov_angle: 1.50098
            decay_acceleration: 1.0
            clear_after_reading: True
          camera_rear:
            topic: "/camera_rear/depth/color/points"
            data_type: "PointCloud2"
            expected_update_rate: 0.0
            min_obstacle_height: 0.05
            max_obstacle_height: 2.0
            marking: True
            clearing: True
            obstacle_range: 3.0
            vertical_fov_angle: 0.994838
            horizontal_fov_angle: 1.50098
            decay_acceleration: 1.0
            clear_after_reading: True 

</details>

<details>
<summary>Log</summary>

[INFO] [launch]: All log files can be found below /home/nattke/.ros/log/2021-11-12-16-17-08-146814-simulation-srv-133904
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [laserscan_multi_merger-1]: process started with pid [133910]
[INFO] [amcl-2]: process started with pid [133912]
[INFO] [map_server-3]: process started with pid [133914]
[INFO] [lifecycle_manager-4]: process started with pid [133916]
[INFO] [controller_server-5]: process started with pid [133918]
[INFO] [planner_server-6]: process started with pid [133920]
[INFO] [recoveries_server-7]: process started with pid [133922]
[INFO] [bt_navigator-8]: process started with pid [133924]
[INFO] [lifecycle_manager-9]: process started with pid [133926]
[INFO] [ros_control-10]: process started with pid [133928]
[laserscan_multi_merger-1] 1636730228.506364 [0] laserscan_: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[lifecycle_manager-4] 1636730228.506840 [0] lifecycle_: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[amcl-2] 1636730228.507029 [0]       amcl: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[lifecycle_manager-9] 1636730228.507884 [0] lifecycle_: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[ros_control-10] 1636730228.507898 [0] ros_contro: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[planner_server-6] 1636730228.508429 [0] planner_se: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[controller_server-5] 1636730228.508899 [0] controller: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[map_server-3] 1636730228.508920 [0] map_server: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[recoveries_server-7] 1636730228.509242 [0] recoveries: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[lifecycle_manager-4] [INFO] [1636730228.510754558] [lifecycle_manager_localization]: Creating
[ros_control-10] [INFO] [1636730228.511187393] [ros_control]: Starting ROS Control
[ros_control-10] [INFO] [1636730228.511235223] [ros_control]: Namespace: /
[ros_control-10] [INFO] [1636730228.511244773] [ros_control]: Name: ros_control
[lifecycle_manager-9] [INFO] [1636730228.511840081] [lifecycle_manager_navigation]: Creating
[bt_navigator-8] 1636730228.513574 [0] bt_navigat: using network interface enp6s0 (udp/10.1.48.11) selected arbitrarily from: enp6s0, docker0
[lifecycle_manager-4] [INFO] [1636730228.514460772] [lifecycle_manager_localization]: Creating and initializing lifecycle service clients
[planner_server-6] [INFO] [1636730228.514787806] [planner_server]: 
[planner_server-6]      planner_server lifecycle node launched. 
[planner_server-6]      Waiting on external lifecycle transitions to activate
[planner_server-6]      See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-4] [INFO] [1636730228.515695846] [lifecycle_manager_localization]: Starting managed nodes bringup...
[lifecycle_manager-4] [INFO] [1636730228.515717737] [lifecycle_manager_localization]: Configuring amcl
[map_server-3] [INFO] [1636730228.515948929] [map_server]: 
[map_server-3]  map_server lifecycle node launched. 
[map_server-3]  Waiting on external lifecycle transitions to activate
[map_server-3]  See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-3] [INFO] [1636730228.516011340] [map_server]: Creating
[planner_server-6] [INFO] [1636730228.516783899] [planner_server]: Creating
[amcl-2] [INFO] [1636730228.517273435] [amcl]: 
[amcl-2]        amcl lifecycle node launched. 
[amcl-2]        Waiting on external lifecycle transitions to activate
[amcl-2]        See https://design.ros2.org/articles/node_lifecycle.html for more information.
[recoveries_server-7] [INFO] [1636730228.517329086] [recoveries_server]: 
[recoveries_server-7]   recoveries_server lifecycle node launched. 
[recoveries_server-7]   Waiting on external lifecycle transitions to activate
[recoveries_server-7]   See https://design.ros2.org/articles/node_lifecycle.html for more information.
[amcl-2] [INFO] [1636730228.517368856] [amcl]: Creating
[controller_server-5] [INFO] [1636730228.518184536] [controller_server]: 
[controller_server-5]   controller_server lifecycle node launched. 
[controller_server-5]   Waiting on external lifecycle transitions to activate
[controller_server-5]   See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-8] [INFO] [1636730228.519029006] [bt_navigator]: 
[bt_navigator-8]        bt_navigator lifecycle node launched. 
[bt_navigator-8]        Waiting on external lifecycle transitions to activate
[bt_navigator-8]        See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-8] [INFO] [1636730228.519104467] [bt_navigator]: Creating
[lifecycle_manager-9] [INFO] [1636730228.519229989] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[controller_server-5] [INFO] [1636730228.521862541] [controller_server]: Creating controller server
[lifecycle_manager-9] [INFO] [1636730228.522420797] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-9] [INFO] [1636730228.522452018] [lifecycle_manager_navigation]: Configuring controller_server
[controller_server-5] [INFO] [1636730228.527236205] [local_costmap.local_costmap]: 
[controller_server-5]   local_costmap lifecycle node launched. 
[controller_server-5]   Waiting on external lifecycle transitions to activate
[planner_server-6] [INFO] [1636730228.527244685] [global_costmap.global_costmap]: 
[planner_server-6]      global_costmap lifecycle node launched. 
[planner_server-6]      Waiting on external lifecycle transitions to activate
[planner_server-6]      See https://design.ros2.org/articles/node_lifecycle.html for more information.
[amcl-2] [INFO] [1636730228.527581569] [amcl]: Configuring
[amcl-2] [INFO] [1636730228.527654579] [amcl]: initTransforms
[planner_server-6] [INFO] [1636730228.527984483] [global_costmap.global_costmap]: Creating Costmap
[controller_server-5]   See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1636730228.529298059] [local_costmap.local_costmap]: Creating Costmap
[amcl-2] [INFO] [1636730228.532750290] [amcl]: initPubSub
[amcl-2] [INFO] [1636730228.535224390] [amcl]: Subscribed to map topic.
[lifecycle_manager-4] [INFO] [1636730228.542749849] [lifecycle_manager_localization]: Configuring map_server
[map_server-3] [INFO] [1636730228.545727705] [map_server]: Configuring
[map_server-3] [INFO] [map_io]: Loading yaml file: /home/ott/config/map/ba_valhalla.yaml
[map_server-3] [DEBUG] [map_io]: resolution: 0.05
[map_server-3] [DEBUG] [map_io]: origin[0]: -20.8
[map_server-3] [DEBUG] [map_io]: origin[1]: -13.3
[map_server-3] [DEBUG] [map_io]: origin[2]: 0
[map_server-3] [DEBUG] [map_io]: free_thresh: 0.25
[map_server-3] [DEBUG] [map_io]: occupied_thresh: 0.65
[map_server-3] [DEBUG] [map_io]: mode: trinary
[map_server-3] [DEBUG] [map_io]: negate: 0
[map_server-3] [INFO] [map_io]: Loading image_file: /home/ott/config/map/ba_valhalla.pgm
[controller_server-5] [INFO] [1636730228.556112339] [controller_server]: Configuring controller interface
[controller_server-5] [INFO] [1636730228.556658545] [controller_server]: Controller frequency set to 10.0000Hz
[controller_server-5] [INFO] [1636730228.556688416] [local_costmap.local_costmap]: Configuring
[controller_server-5] [INFO] [1636730228.559065174] [local_costmap.local_costmap]: Using plugin "static_layer"
[controller_server-5] [INFO] [1636730228.560995567] [local_costmap.local_costmap]: Subscribing to the map topic (/map) with transient local durability
[controller_server-5] [INFO] [1636730228.561391542] [local_costmap.local_costmap]: Initialized plugin "static_layer"
[controller_server-5] [INFO] [1636730228.561405102] [local_costmap.local_costmap]: Using plugin "obstacle_2d_layer"
[controller_server-5] [INFO] [1636730228.561739346] [local_costmap.local_costmap]: Subscribed to Topics: scan_front scan_rear
[controller_server-5] [INFO] [1636730228.564367897] [local_costmap.local_costmap]: Initialized plugin "obstacle_2d_layer"
[controller_server-5] [INFO] [1636730228.564389357] [local_costmap.local_costmap]: Using plugin "obstacle_3d_layer"
[map_server-3] [DEBUG] [map_io]: Read map /home/ott/config/map/ba_valhalla.pgm: 832 X 534 map @ 0.05 m/cell
[lifecycle_manager-4] [INFO] [1636730228.574564398] [lifecycle_manager_localization]: Activating amcl
[amcl-2] [INFO] [1636730228.574724140] [amcl]: Activating
[amcl-2] [WARN] [1636730228.574751481] [amcl]: Publishing the particle cloud as geometry_msgs/PoseArray msg is deprecated, will be published as nav2_msgs/ParticleCloud in the future
[amcl-2] [INFO] [1636730228.574764581] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1636730228.574857752] [amcl]: Setting pose (488.996000): 0.000 0.000 0.000
[lifecycle_manager-4] [INFO] [1636730228.575513070] [lifecycle_manager_localization]: Activating map_server
[map_server-3] [INFO] [1636730228.575603331] [map_server]: Activating
[controller_server-5] [INFO] [1636730228.576935157] [local_costmap.local_costmap]: obstacle_3d_layer being initialized as SpatioTemporalVoxelLayer!
[controller_server-5] [INFO] [1636730228.576960317] [local_costmap.local_costmap]: obstacle_3d_layer's global frame is map.
[controller_server-5] [INFO] [1636730228.577839317] [local_costmap.local_costmap]: obstacle_3d_layer loaded parameters from parameter server.
[controller_server-5] [INFO] [1636730228.579880952] [local_costmap.local_costmap]: obstacle_3d_layer created underlying voxel grid.
[controller_server-5] [INFO] [1636730228.581329600] [local_costmap.local_costmap]: Passthough filter activated.
[amcl-2] [INFO] [1636730228.583162921] [amcl]: Received a 832 X 534 map @ 0.050 m/pix
[lifecycle_manager-4] [INFO] [1636730228.583160921] [lifecycle_manager_localization]: Managed nodes are active
[controller_server-5] [INFO] [1636730228.583277093] [local_costmap.local_costmap]: StaticLayer: Resizing static layer to 832 X 534 at 0.050000 m/pix
[controller_server-5] [INFO] [1636730228.584404896] [local_costmap.local_costmap]: Passthough filter activated.
[controller_server-5] [INFO] [1636730228.585887684] [local_costmap.local_costmap]: Passthough filter activated.
[controller_server-5] [INFO] [1636730228.587681595] [local_costmap.local_costmap]: Passthough filter activated.
[controller_server-5] [INFO] [1636730228.588097680] [local_costmap.local_costmap]: obstacle_3d_layer initialization complete!
[controller_server-5] [INFO] [1636730228.588115250] [local_costmap.local_costmap]: Initialized plugin "obstacle_3d_layer"
[controller_server-5] [INFO] [1636730228.588126221] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-5] [INFO] [1636730228.588489245] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-5] [INFO] [1636730228.591148076] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-5] [INFO] [1636730228.591516881] [controller_server]: Created goal_checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-5] [INFO] [1636730228.592358701] [controller_server]: Created controller : ba_controller of type ba_controller::Controller
[controller_server-5] [INFO] [1636730228.594369495] [controller_server]: Controller Server has ba_controller  controllers available.
[lifecycle_manager-9] [INFO] [1636730228.596499850] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-6] [INFO] [1636730228.596695312] [planner_server]: Configuring
[planner_server-6] [INFO] [1636730228.596730323] [global_costmap.global_costmap]: Configuring
[planner_server-6] [INFO] [1636730228.599027120] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-6] [INFO] [1636730228.601225876] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-6] [INFO] [1636730228.601673262] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-6] [INFO] [1636730228.601690802] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-6] [INFO] [1636730228.603066298] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-6] [INFO] [1636730228.607123607] [planner_server]: Created global planner plugin grid_based of type nav2_navfn_planner/NavfnPlanner
[planner_server-6] [INFO] [1636730228.607147037] [planner_server]: Configuring plugin grid_based of type NavfnPlanner
[planner_server-6] [INFO] [1636730228.609786819] [planner_server]: Created global planner plugin straight_path of type straight_path_planner/StraightPathPlanner
[planner_server-6] [INFO] [1636730228.609904250] [planner_server]: Planner Server has grid_based straight_path  planners available.
[lifecycle_manager-9] [INFO] [1636730228.611917414] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-7] [INFO] [1636730228.612088126] [recoveries_server]: Configuring
[planner_server-6] [INFO] [1636730228.612907126] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 832 X 534 at 0.050000 m/pix
[recoveries_server-7] [INFO] [1636730228.614653567] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-7] [INFO] [1636730228.615376176] [recoveries_server]: Configuring spin
[recoveries_server-7] [INFO] [1636730228.616769172] [recoveries_server]: Creating recovery plugin back_up of type nav2_recoveries/BackUp
[recoveries_server-7] [INFO] [1636730228.617301108] [recoveries_server]: Configuring back_up
[recoveries_server-7] [INFO] [1636730228.618089018] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-7] [INFO] [1636730228.618562743] [recoveries_server]: Configuring wait
[lifecycle_manager-9] [INFO] [1636730228.620196043] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-8] [INFO] [1636730228.620351995] [bt_navigator]: Configuring
[bt_navigator-8] [INFO] [1636730228.632859734] [bt_navigator_rclcpp_node]: Waiting for "compute_path_to_pose" action server
[bt_navigator-8] [INFO] [1636730228.633004905] [bt_navigator_rclcpp_node]: "ComputePathToPose" BtActionNode initialized
[bt_navigator-8] [INFO] [1636730228.633349279] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-8] [INFO] [1636730228.633463421] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Context" BtServiceNode initialized
[bt_navigator-8] [INFO] [1636730228.634898288] [bt_navigator_rclcpp_node]: Waiting for "follow_path" action server
[bt_navigator-8] [INFO] [1636730228.634989439] [bt_navigator_rclcpp_node]: "FollowPath" BtActionNode initialized
[bt_navigator-8] [INFO] [1636730228.635331503] [bt_navigator_rclcpp_node]: Waiting for "local_costmap/clear_entirely_local_costmap" service
[bt_navigator-8] [INFO] [1636730228.635395224] [bt_navigator_rclcpp_node]: "ClearLocalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-8] [INFO] [1636730228.635703998] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-8] [INFO] [1636730228.635765188] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-8] [INFO] [1636730228.637278587] [bt_navigator_rclcpp_node]: Waiting for "wait" action server
[bt_navigator-8] [INFO] [1636730228.637369408] [bt_navigator_rclcpp_node]: "Wait" BtActionNode initialized
[bt_navigator-8] [INFO] [1636730228.638746674] [bt_navigator_rclcpp_node]: Waiting for "wait" action server
[bt_navigator-8] [INFO] [1636730228.638835195] [bt_navigator_rclcpp_node]: "Wait" BtActionNode initialized
[bt_navigator-8] [INFO] [1636730228.639118529] [bt_navigator_rclcpp_node]: Waiting for "local_costmap/clear_entirely_local_costmap" service
[bt_navigator-8] [INFO] [1636730228.639161319] [bt_navigator_rclcpp_node]: "ClearLocalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-8] [INFO] [1636730228.639408212] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-8] [INFO] [1636730228.639467743] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-8] [INFO] [1636730228.640678657] [bt_navigator_rclcpp_node]: Waiting for "wait" action server
[bt_navigator-8] [INFO] [1636730228.640749878] [bt_navigator_rclcpp_node]: "Wait" BtActionNode initialized
[lifecycle_manager-9] [INFO] [1636730228.641984303] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-5] [INFO] [1636730228.642205386] [controller_server]: Activating
[controller_server-5] [INFO] [1636730228.642242276] [local_costmap.local_costmap]: Activating
[controller_server-5] [INFO] [1636730228.642255566] [local_costmap.local_costmap]: Checking transform
[controller_server-5] [INFO] [1636730228.642288377] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730229.066491405] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 488.971 for reason 'Unknown'
[amcl-2] [INFO] [1636730229.141000123] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1636730229.141074584] [amcl]: Setting pose (489.502000): -4.071 -6.631 -2.469
[controller_server-5] [INFO] [1636730229.142342879] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730229.375010963] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 488.971 for reason 'Unknown'
[controller_server-5] [INFO] [1636730229.467774689] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 488.971 for reason 'Unknown'
[controller_server-5] [INFO] [1636730229.568230197] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 489.610 for reason 'Unknown'
[controller_server-5] [INFO] [1636730229.642343380] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730229.770017992] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 489.610 for reason 'Unknown'
[controller_server-5] [INFO] [1636730229.971047679] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 489.610 for reason 'Unknown'
[controller_server-5] [INFO] [1636730230.142331841] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730230.272220589] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 490.263 for reason 'Unknown'
[controller_server-5] [INFO] [1636730230.372684546] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 490.263 for reason 'Unknown'
[controller_server-5] [INFO] [1636730230.473261405] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 490.263 for reason 'Unknown'
[controller_server-5] [INFO] [1636730230.642342601] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730230.974991425] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 490.854 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.075213619] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 490.854 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.142292859] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730231.276743011] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 490.854 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.477723676] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 490.854 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.478489915] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 491.517 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.642335608] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730231.680050397] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 491.517 for reason 'Unknown'
[controller_server-5] [INFO] [1636730231.780230261] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 491.517 for reason 'Unknown'
[amcl-2] [INFO] [1636730231.785281901] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1636730231.785380682] [amcl]: Setting pose (492.208000): -3.907 -6.954 -2.129
[controller_server-5] [INFO] [1636730231.980652219] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 491.517 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.142349895] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730232.282309203] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 492.114 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.382423995] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 492.114 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.483336388] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_rear_depth_optical_frame' at time 492.114 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.584957759] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 492.114 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.642343833] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730232.785531108] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 492.757 for reason 'Unknown'
[controller_server-5] [INFO] [1636730232.985770234] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 492.757 for reason 'Unknown'
[controller_server-5] [INFO] [1636730233.142339608] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[controller_server-5] [INFO] [1636730233.187405135] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 492.757 for reason 'Unknown'
[controller_server-5] [INFO] [1636730233.387980575] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 493.387 for reason 'Unknown'
[laserscan_multi_merger-1] [INFO] [1636730233.518903044] [laserscan_multi_merger]: Subscribing to 2 topics.
[laserscan_multi_merger-1] [INFO] [1636730233.519426510] [laserscan_multi_merger]: Subscribed to scan_front.
[laserscan_multi_merger-1] [INFO] [1636730233.519603632] [laserscan_multi_merger]: Subscribed to scan_rear.
[amcl-2] [INFO] [1636730233.553118081] [amcl]: createLaserObject
[controller_server-5] [INFO] [1636730233.588674865] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 493.387 for reason 'Unknown'
[controller_server-5] [INFO] [1636730233.642423585] [local_costmap.local_costmap]: start
[controller_server-5] [INFO] [1636730233.644183466] [local_costmap.local_costmap]: obstacle_3d_layer was activated.
[controller_server-5] [INFO] [1636730233.646818147] [controller_server]: Activating controller: ba_controller of type ba_controller::Controller
[lifecycle_manager-9] [INFO] [1636730233.647296663] [lifecycle_manager_navigation]: Activating planner_server
[planner_server-6] [INFO] [1636730233.647446835] [planner_server]: Activating
[planner_server-6] [INFO] [1636730233.647480525] [global_costmap.global_costmap]: Activating
[planner_server-6] [INFO] [1636730233.647490145] [global_costmap.global_costmap]: Checking transform
[planner_server-6] [INFO] [1636730233.647554836] [global_costmap.global_costmap]: start
[planner_server-6] [INFO] [1636730233.697651813] [planner_server]: Activating plugin straight_path of type NavfnPlanner
[planner_server-6] [INFO] [1636730233.697700783] [planner_server]: Activating plugin grid_based of type NavfnPlanner
[lifecycle_manager-9] [INFO] [1636730233.698176549] [lifecycle_manager_navigation]: Activating recoveries_server
[recoveries_server-7] [INFO] [1636730233.698349461] [recoveries_server]: Activating
[recoveries_server-7] [INFO] [1636730233.698377761] [recoveries_server]: Activating spin
[recoveries_server-7] [INFO] [1636730233.698390042] [recoveries_server]: Activating back_up
[recoveries_server-7] [INFO] [1636730233.698397182] [recoveries_server]: Activating wait
[lifecycle_manager-9] [INFO] [1636730233.698678795] [lifecycle_manager_navigation]: Activating bt_navigator
[bt_navigator-8] [INFO] [1636730233.698845617] [bt_navigator]: Activating
[lifecycle_manager-9] [INFO] [1636730233.699127910] [lifecycle_manager_navigation]: Managed nodes are active
[controller_server-5] [INFO] [1636730233.790007053] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 493.387 for reason 'Unknown'
[controller_server-5] [INFO] [1636730233.991032307] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 493.974 for reason 'Unknown'
[controller_server-5] [INFO] [1636730234.092932970] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 493.974 for reason 'Unknown'
[controller_server-5] [INFO] [1636730234.594339821] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_front_depth_optical_frame' at time 494.587 for reason 'Unknown'
[controller_server-5] [INFO] [1636730234.793333741] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_left_depth_optical_frame' at time 494.587 for reason 'Unknown'
[bt_navigator-8] [INFO] [1636730236.402458677] [bt_navigator]: Begin navigating from current location to (-0.52, -6.20)
[controller_server-5] [INFO] [1636730236.425761205] [controller_server]: Received a goal, begin computing control effort.
[controller_server-5] [INFO] [1636730240.526067084] [controller_server]: Reached the goal!
[bt_navigator-8] [INFO] [1636730240.563149096] [bt_navigator]: Navigation succeeded

</details>
 

Edit: I'm aware that the log spits out some dropping messages from Message Filter but these stops when i set an inital pose (and map > odom is available)

**Comment by SteveMacenski** [comment]
>  [controller_server-5] [INFO] [1636730233.790007053] [local_costmap.local_costmap_rclcpp_node]: Message Filter dropping message: frame 'camera_right_depth_optical_frame' at time 493.387 for reason 'Unknown'

That means you're not setting up your frames correctly. Please analyze your TF tree and make sure the transformations that need to be made available for the data to be processed are available. You're dropping messages in the TF message filter because the necessary transformations aren't available at run-time to allow the data to enter the callbacks to be transformed and meaningfully used. 

For followup, please ask on ROS Answers. This is a setup related issue.
