### ISSUE TITLE
Deadlock introduced with latest commit on noetic-devel

### ISSUE THREAD

**Issue by onjen** [SteveMacenski/spatio_temporal_voxel_layer#246]
As @corot noted in this [PR](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/243#issuecomment-1354020938), the [latest commit](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/commit/1cc77c7540b160488dbefe62bf80a750c22425fc) on noetic-devel introduces a deadlock.

Can you revert the commit until the fix is developed?

**Comment by SteveMacenski** [comment]
@onjen can you test out https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/245 and let me know if that resolves your issue? I'll merge then and we're good to go

**Comment by onjen** [comment]
Tested #245 and it fixes the issue
