### ISSUE TITLE
cuPCL usage with this package

### ISSUE THREAD

**Issue by tugbakara** [SteveMacenski/spatio_temporal_voxel_layer#248]
Hi @SteveMacenski ,hope you're being well !  :)
I have Jetson AGX , and searched about PCL library to use it with GPU I reached two things but not sure to use with **spatio_temporal_voxel_layer** :

1. Installing PCL with CUDA support
2. Using cuPCL with this package but not sure is it usable.
That's why come here. Is spatio_temporal_voxel_layer can be usable with cuPCL? If not, I will install PCL with CUDA support will it affect the performance, any idea?
Thanks!

**Comment by SteveMacenski** [comment]
There is no cuda support for this package since the core library also doesn't support cuda in openvdb.
