### ISSUE TITLE
Unused Parameter "unknown_threshold"

### ISSUE THREAD

**Issue by borongyuan** [SteveMacenski/spatio_temporal_voxel_layer#254]
Hi, in the docs and examples there is a parameter "unknown_threshold". But we don't see the relevant part in the code. Did I miss something?

**Comment by SteveMacenski** [comment]
Nope, I think that was probably removed at some point and the documentation and yaml files weren't updated to reflect that. A PR to remove those would be appreciated :smile:

**Comment by GeorgiosGkovo** [comment]
Hi @borongyuan, I think that "unknown_threshold" is a parameter that is passed to the layer under STVL. If I am not mistaken this must be something like "costmap_2d".

**Comment by SteveMacenski** [comment]
Its not, they’re old artifacts
