### ISSUE TITLE
Using STVL with SLAM

### ISSUE THREAD

**Issue by amit-z** [SteveMacenski/spatio_temporal_voxel_layer#260]
If I understood correctly, it is possible to use mapping with STVL, but you can't use voxel decay at the same time?
Is there a way to combine STVL and SLAM (let's say, the slam provided by ZED sterolabs?)

**Comment by SteveMacenski** [comment]
STVL is not SLAM - but you can use any state estimation system you like in conjunction with STVL for planning and control as you would any obstacle marking layer
