### ISSUE TITLE
Should I be using RTABMAP with STVL and Nav2? How do I configure parameters in ROS2?

### ISSUE THREAD

**Issue by Roozki** [SteveMacenski/spatio_temporal_voxel_layer#265]
I am using ROS2 Foxy and Ubuntu 20.04
Hello, I am more or less new to navigation in ROS, and was hoping for some guidance.
If anyone could share their full setup steps that would be very helpful.
I am using a ZED2i and a 16 channel 3d lidar (similar to the VLP16 ).

I am able to get Nav2 to publish to /cmd_vel after defining a goal, with lidar+RGBD odometry + mapping from rtabmap. However dynamic obstacles mess up the mapping and localization. So I want to use STVL, I was able to get it started, but no voxels are being published. 

Happy to provide any of my files, but I'm looking for some general resources or any sort of direction. I am using RTABMAP to publish my map and odometry, and its working pretty well. I have a feeling I've set up my stack with redundant parts. If someone could send me a full example of RTABMAP with STVL and Nav2 that would be awesome, or explain why it wouldn't make sense to use STVL with RTABMAP.

My end goal is to have realtime mapping, localizing and planning with dynamic obstacles, using ROS2 and the Zed2i camera and 3d lidar. Any help is greatly appreciated, thank you in advance

**Comment by SteveMacenski** [comment]
This is better suited for ROS Answers / Robotics Stack Exchange. If you file a question, I'll respond there (feel free to link it here). But this isn't the right place for system-integration level questions.

Please include some pictures of what you mean by "dynamic obstacles mess up the mapping and localization" --> BTW STVL isn't a localization solution, only for collision avoidance.

**Comment by Roozki** [comment]
thank you for your quick response! I will check there for any similar questions, and maybe post my own if I need to. I think I am on the right track as I am trying to use STVL for collision avoidance. Thank you for your advice, STVL is incredibly interesting so thank you for sharing and documenting it.
