### ISSUE TITLE
How can I know the changes of each release?

### ISSUE THREAD

**Issue by corot** [SteveMacenski/spatio_temporal_voxel_layer#283]
I see that the last noetic package version is 1.4.5-1focal.20240111.191302, but I don's see what changed since 1.4.5-0.
Is 2024-01-11 the creation date?  Does it contain #271 and #272?

If not, can we do a new release containing latest fixes?

Thanks!

**Comment by SteveMacenski** [comment]
Nothing has changed in ROS 1, in recent memory and it receives no support at this point. Move to ROS 2 :-)

**Comment by corot** [comment]
:crying_cat_face: 
roger,,,  thanks for the info
I wish I could rn! but will take some time
