### ISSUE TITLE
Possible bug in operator() for marking voxels?

### ISSUE THREAD

**Issue by xaru8145** [SteveMacenski/spatio_temporal_voxel_layer#292]
Hi,

I noticed [L295](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/ros2/spatio_temporal_voxel_layer/src/spatio_temporal_voxel_grid.cpp#L295) of spatio_temporal_voxel_grid cpp file uses the value of `iter_y` to determine the value of `z`
`double z = *iter_y < 0 ? *iter_z - _voxel_size : *iter_z; `
Is this intended or shoud it be this way?
`double z = *iter_z < 0 ? *iter_z - _voxel_size : *iter_z; `

Thanks for your time!

**Comment by SteveMacenski** [comment]
I'm pretty sure that's a typo. @KavenYau this is from your PR a little over a year ago. Do you agree this is just a typo that we should fix?

**Comment by KavenYau** [comment]
> I'm pretty sure that's a typo. @KavenYau this is from your PR a little over a year ago. Do you agree this is just a typo that we should fix?

Yes, it's definitely a typo. :frowning:

**Comment by SteveMacenski** [comment]
@xaru8145 can you submit a PR? :smile:

**Comment by xaru8145** [comment]
Done @SteveMacenski ! PR #293
