### ISSUE TITLE
Possible typo? - Callback group not set for PublisherOptions

### ISSUE THREAD

**Issue by ivrolan** [SteveMacenski/spatio_temporal_voxel_layer#297]
In `ros2` and `humble` branch, in `spatio_temporal_voxel_layer.cpp`, the subscriber and publisher options are set in [this way](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/ros2/spatio_temporal_voxel_layer/src/spatio_temporal_voxel_layer.cpp#L143-L147):

    auto sub_opt = rclcpp::SubscriptionOptions();
    sub_opt.callback_group = callback_group_;

    auto pub_opt = rclcpp::PublisherOptions();
    sub_opt.callback_group = callback_group_;

Note how the `sub_opt.callback_group = callback_group_` is set twice, and the `pub_opt` is left as the default. Is this intended?

**Comment by SteveMacenski** [comment]
Looks like a typo to me, this isn't a big deal but certainly would be a good PR to have fixed! Can you submit that @ivrolan?

**Comment by ivrolan** [comment]
Sure! I'll test it and open the PR

**Comment by SteveMacenski** [comment]
Merging! Thanks for the report
