### ISSUE TITLE
Release for Jazzy?

### ISSUE THREAD

**Issue by tonynajjar** [SteveMacenski/spatio_temporal_voxel_layer#299]
Probably you have it in mind already but didn't find any ticket that tracks it so here it is

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/42121 done

**Comment by Rayman** [comment]
For some reason the build did not succeed. Did the agent run out of memory (OOM killer)?

```
08:31:11 c++: fatal error: Killed signal terminated program cc1plus
```

https://build.ros2.org/job/Jbin_uN64__openvdb_vendor__ubuntu_noble_amd64__binary/9/console

**Comment by Timple** [comment]
https://discourse.ros.org/t/new-packages-for-jazzy-jalisco-2024-07-23/38746/2?u=timple

:cry:

**Comment by Timple** [comment]
Ah, @Rayman came to a different conclusion. That seems more likely to be the rootcause :+1:
