### ISSUE TITLE
Inconsistent behavior for update rate between stvl and navigation2/nav2_costmap_2d

### ISSUE THREAD

**Issue by sjusner** [SteveMacenski/spatio_temporal_voxel_layer#307]
When comparing the behavior of the stvl and the nav2 obstacle layer some differences in behavior emerged during troubleshooting an issue. In the obstacle_layer (more precisely the used observation buffer) stale observations get purged when they are older than the specified `observation_keep_time_` (set via the `observation_persistence` parameter) compared to `clock_->now() [here](https://github.com/ros-navigation/navigation2/blob/dc26fa46d9240763af0cfc17f5b8a124f085eb41/nav2_costmap_2d/src/observation_buffer.cpp#L202). For the stvl, this is compared to the last update time [here](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/0b76e8d84ca381bb4d72f4631bb30132d7c68d9c/spatio_temporal_voxel_layer/src/measurement_buffer.cpp#L221).

This leads to inconsistent behavior when sensor data is suddenly dropping out.
- For the obstacle_layer, the observations get removed from the buffer after the set time as would be expected. 
- The stvl keeps observations past the set `observation_persistence` as stale buffer entries get only removed when new observations are coming in (due to the update of `last_updated_`).

I suggest to replace the stale check in the stvl to compare with the current time instead of the `last_updated_`. Further, as commented in [this issue](https://github.com/ros-navigation/navigation2/issues/4734#issuecomment-2470214807), the update of `last_updated` in the reset function seems misplaced, and interferes with the `expected_update_rate` calculation.

Any thoughts on this?

**Comment by SteveMacenski** [comment]
> compared to `clock_->now() [here](https://github.com/ros-navigation/navigation2/blob/dc26fa46d9240763af0cfc17f5b8a124f085eb41/nav2_costmap_2d/src/observation_buffer.cpp#L202). For the stvl, this is compared to the last update time [here](https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/0b76e8d84ca381bb4d72f4631bb30132d7c68d9c/spatio_temporal_voxel_layer/src/measurement_buffer.cpp#L221).

I checked some of the older git commits and it looks like the behavior in Nav2 was updated but STVL wasn't updated with it. This used to be how Nav2's / ROS Navigation's observation buffer handled it. 

Here's the PR that made the change in Nav2 https://github.com/ros-navigation/navigation2/pull/1872

Id support that update. Can you open the PR?
