### ISSUE TITLE
Voxel grid and costmap stop marking

### ISSUE THREAD

**Issue by tasilb** [SteveMacenski/spatio_temporal_voxel_layer#43]
Observed this after the costmap reset was triggered and when there were a lot of voxels left marked. Normal behavior was restored after the grid was purged by another reset or when all previously marked voxels expired

**Comment by SteveMacenski** [comment]
probably just fixed

reopen if not true

**Comment by tasilb** [comment]
Still not fixed, observed again even with not as many marked voxels

**Comment by SteveMacenski** [comment]
this has nothing to do with the number of voxels marked, it has to do with the reset operation apparently.

**Comment by SteveMacenski** [comment]
https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/kinetic-devel/src/spatio_temporal_voxel_layer.cpp#L391

https://github.com/ros-planning/navigation/blob/53087ca5242fb40f06c84a6bcc74057c3470eff7/costmap_2d/plugins/obstacle_layer.cpp#L578

**Comment by SteveMacenski** [comment]
similar issue appears in the mapping publisher at 1hz. interesting.

**Comment by SteveMacenski** [comment]
I think this is from dirty configs, closing again, but may reopen
