### ISSUE TITLE
remove excess reset

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/spatio_temporal_voxel_layer#51]
https://github.com/SteveMacenski/spatio_temporal_voxel_layer/blob/deae202a5672de99f21617af082c19bac776c8fc/src/spatio_temporal_voxel_layer.cpp#L535

**Comment by tasilb** [comment]
This will be rolled in as part of #49

**Comment by SteveMacenski** [comment]
Rolled into 49
