### ISSUE TITLE
build with Melodic

### ISSUE THREAD

**Issue by SteveMacenski** [SteveMacenski/spatio_temporal_voxel_layer#65]

**Comment by doisyg** [comment]
I just tried, it doesn't compil by default. Mainly, I believe, because costmap_2d::Layer uses now a tf2_ros::Buffer in its initialize method instead of a tf::TransformListener.
This implies that part of the code will have to be converted to tf2

**Comment by SteveMacenski** [comment]
PRs are welcome

**Comment by doisyg** [comment]
Just managed to compile, I will do some tests and then a PR around next week

**Comment by SteveMacenski** [comment]
Awesome, I'll make a Melodic devel branch and run some tests quickly in 18.04 to make sure it's all clean once you PR.

**Comment by doisyg** [comment]
https://github.com/SteveMacenski/spatio_temporal_voxel_layer/pull/81
